### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

### ISSUE THREAD

**Issue by chandraprakash4790** [Gladiator07/JARVIS#21]
You said: jarvis take a screenshot
Traceback (most recent call last):
  File "c:\Users\venky\Downloads\JARVIS-master\JARVIS-master\main.py", line 108, in run
    self.TaskExecution()
  File "c:\Users\venky\Downloads\JARVIS-master\JARVIS-master\main.py", line 231, in TaskExecution
    obj.google_calendar_events(command)
  File "c:\Users\venky\Downloads\JARVIS-master\JARVIS-master\Jarvis\__init__.py", line 126, in google_calendar_events    
    service = google_calendar.authenticate_google()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\venky\Downloads\JARVIS-master\JARVIS-master\Jarvis\features\google_calendar.py", line 48, in authenticate_google
    flow = InstalledAppFlow.from_client_secrets_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\venky\AppData\Local\Programs\Python\Python311\Lib\site-packages\google_auth_oauthlib\flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

**Comment by MrSpideyNihal** [comment]
Create a file first named as client_secrets_file.json
