### ISSUE TITLE
I keep getting the message "ModuleNotFoundError: No module named 'speech_recognition'" and it wont launch the program.

### ISSUE THREAD

**Issue by Skippostle** [Gladiator07/JARVIS#7]

**Comment by Dev-98** [comment]
To beta module install karo programming karne chale ho itna bhi nahi aata. Copy paste this line in your cmd(command prompt) "pip install SpeechRecognition'' net se connect hona chahiye laptop , pc whatever. Iske baad bhi error aaye to chutiye beta programming bhul jana tum jaise chutiyo ke liye nahi bana

**Comment by AnnKont** [comment]
> To beta module install karo programming karne chale ho itna bhi nahi aata. Copy paste this line in your cmd(command prompt) "pip install SpeechRecognition'' net se connect hona chahiye laptop , pc whatever. Iske baad bhi error aaye to chutiye beta programming bhul jana tum jaise chutiyo ke liye nahi bana

I have same problem.

`pip install SpeechRecognition`
`Requirement already satisfied: SpeechRecognition in c:\users\...\miniconda3\lib\site-packages (3.8.1)`

But when I try do `python main.py`, I have this:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from Jarvis import JarvisAssistant
  File "__init__.py", line 1, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'
```
